version: '3.8'

services:
  apicentral:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5149:5149"   # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5149
      - ConnectionStrings__DefaultConnection=Host=grafica-mvp-postgres.csxueyi2miv2.us-east-1.rds.amazonaws.com;Database=bpdapi_db;Username=postgres;Password=GraficaMVP2025!;Port=5432
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=GraficaMVP2025!
      - RabbitMQ__Port=5672
      - RabbitMQ__QueueName=lote.processamento
      - RabbitMQ__ExchangeName=graficaltda.exchange
    volumes:
      - ./appsettings.Development.json:/app/appsettings.Development.json:ro
    restart: unless-stopped
    networks:
      - grafica-net

networks:
  grafica-net:
    external: true
